# Abstract {.unnumbered .unlisted}

The goal of the internship was to study the combination of LiDAR point clouds and aerial images in a deep learning model to identify individual trees, and in particular those covered by other trees. To do this, I modified a model capable of merging LiDAR and RGB data to feed it with more information about the geometry below the canopy surface. This required to create my own tree dataset, using publicly available data from the Netherlands. A few interesting results emerged and the model proved its ability to quickly learn to find large and medium trees, even with a small training dataset. However, this new pipeline should be evaluated on a larger dataset to precisely determine the influence of the modifications on the performance regarding small and covered trees.

The source code for this report can be found [here](https://github.com/alexandre-bry/Geodan-internship-report)^[[https://github.com/alexandre-bry/Geodan-internship-report](https://github.com/alexandre-bry/Geodan-internship-report)] and the online version is [here](https://alexandre-bry.github.io/Geodan-internship-report)^[[https://alexandre-bry.github.io/Geodan-internship-report](https://alexandre-bry.github.io/Geodan-internship-report)]. The source code for the project can be found [here](https://github.com/sogelink-research/tree-segmentation)^[[https://github.com/sogelink-research/tree-segmentation](https://github.com/sogelink-research/tree-segmentation)].
